// Code generated by protoc-gen-go.
// source: addressbook.proto
// DO NOT EDIT!

/*
Package proto_struct is a generated protocol buffer package.

It is generated from these files:
	addressbook.proto
	testproto.proto

It has these top-level messages:
	Person
	Ext
	AddressBook
	TestProto
*/
package proto_struct

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) Enum() *Person_PhoneType {
	p := new(Person_PhoneType)
	*p = x
	return p
}
func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (x *Person_PhoneType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Person_PhoneType_value, data, "Person_PhoneType")
	if err != nil {
		return err
	}
	*x = Person_PhoneType(value)
	return nil
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	Name             *string                   `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Id               *int32                    `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Email            *string                   `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phone            []*Person_PhoneNumber     `protobuf:"bytes,4,rep,name=phone" json:"phone,omitempty"`
	Test             []int32                   `protobuf:"varint,5,rep,packed,name=test" json:"test,omitempty"`
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

var extRange_Person = []proto.ExtensionRange{
	{10, 536870911},
}

func (*Person) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Person
}
func (m *Person) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

func (m *Person) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *Person) GetPhone() []*Person_PhoneNumber {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *Person) GetTest() []int32 {
	if m != nil {
		return m.Test
	}
	return nil
}

type Person_PhoneNumber struct {
	Number           *string           `protobuf:"bytes,1,req,name=number" json:"number,omitempty"`
	Type             *Person_PhoneType `protobuf:"varint,2,opt,name=type,enum=proto_struct.Person_PhoneType,def=1" json:"type,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

const Default_Person_PhoneNumber_Type Person_PhoneType = Person_HOME

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_Person_PhoneNumber_Type
}

type Ext struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Ext) Reset()                    { *m = Ext{} }
func (m *Ext) String() string            { return proto.CompactTextString(m) }
func (*Ext) ProtoMessage()               {}
func (*Ext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

var E_Ext_Test = &proto.ExtensionDesc{
	ExtendedType:  (*Person)(nil),
	ExtensionType: (*int32)(nil),
	Field:         10,
	Name:          "proto_struct.Ext.test",
	Tag:           "varint,10,opt,name=test",
}

// Our address book file is just one of these.
type AddressBook struct {
	Person           *Person `protobuf:"bytes,1,req,name=person" json:"person,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddressBook) Reset()                    { *m = AddressBook{} }
func (m *AddressBook) String() string            { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()               {}
func (*AddressBook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddressBook) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "proto_struct.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "proto_struct.Person.PhoneNumber")
	proto.RegisterType((*Ext)(nil), "proto_struct.Ext")
	proto.RegisterType((*AddressBook)(nil), "proto_struct.AddressBook")
	proto.RegisterEnum("proto_struct.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
	proto.RegisterExtension(E_Ext_Test)
}

var fileDescriptor0 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x4d, 0xda, 0x94, 0xee, 0x74, 0x5d, 0x62, 0xf0, 0x10, 0x3c, 0x48, 0x29, 0x1e, 0xaa,
	0x42, 0x85, 0x7a, 0xf3, 0x66, 0xa1, 0xa0, 0xe8, 0xda, 0x55, 0x04, 0x8f, 0xd2, 0xb5, 0x01, 0x17,
	0x6d, 0x53, 0x9a, 0x2c, 0xe8, 0xcd, 0x5f, 0x2e, 0x4e, 0x5b, 0x91, 0x3d, 0xac, 0xb9, 0xe4, 0x31,
	0xf3, 0xcd, 0xbc, 0xc7, 0xc0, 0x5e, 0x59, 0x55, 0x9d, 0x32, 0x66, 0xa9, 0xf5, 0x5b, 0xd2, 0x76,
	0xda, 0x6a, 0x31, 0x1d, 0xbe, 0x67, 0x63, 0xbb, 0xf5, 0x8b, 0x8d, 0xbe, 0x09, 0x78, 0x0b, 0xd5,
	0x19, 0xdd, 0x88, 0x29, 0xb8, 0x4d, 0x59, 0x2b, 0x49, 0x42, 0x1a, 0x4f, 0x04, 0x00, 0x5d, 0x55,
	0x92, 0xa2, 0x66, 0x62, 0x17, 0x98, 0xaa, 0xcb, 0xd5, 0xbb, 0x74, 0x42, 0x82, 0xad, 0x33, 0x60,
	0xed, 0xab, 0x6e, 0x94, 0x74, 0x43, 0x27, 0x0e, 0xd2, 0x30, 0xd9, 0xdc, 0x98, 0x8c, 0xdb, 0x92,
	0x45, 0x4f, 0xdc, 0xad, 0xeb, 0xa5, 0xea, 0x04, 0x07, 0xd7, 0x2a, 0x63, 0x25, 0x43, 0x9e, 0x65,
	0x94, 0x93, 0x83, 0x7b, 0x08, 0x36, 0x81, 0x19, 0x78, 0xcd, 0xa0, 0x7e, 0xcd, 0x53, 0x1c, 0xf8,
	0x6c, 0x15, 0xda, 0x93, 0x78, 0x96, 0x1e, 0xfe, 0x6f, 0xf0, 0x88, 0xd4, 0x85, 0x7b, 0x55, 0xcc,
	0xf3, 0xe8, 0x14, 0x26, 0x7f, 0x25, 0x4c, 0xef, 0xcd, 0x8b, 0xec, 0xfa, 0x36, 0xe7, 0x3b, 0xc2,
	0x87, 0x01, 0xe0, 0xa4, 0x57, 0x4f, 0xc5, 0xc3, 0x0d, 0xa7, 0x27, 0xbe, 0x0f, 0xfc, 0x0b, 0x1f,
	0x8d, 0x8e, 0xc1, 0xc9, 0x3f, 0x6c, 0x1a, 0x8d, 0x11, 0xc5, 0xfe, 0x36, 0x2f, 0x09, 0x98, 0x83,
	0x45, 0xe7, 0x10, 0x5c, 0x8e, 0xe7, 0xcc, 0xf0, 0x9c, 0xe2, 0x08, 0xbc, 0x76, 0x6c, 0xf7, 0xa1,
	0x83, 0x74, 0xeb, 0xe8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x72, 0x3a, 0xad, 0x8f, 0x82, 0x01,
	0x00, 0x00,
}
